apiVersion: v1
kind: Service
metadata:
  name: driver-service
  namespace: lastmile
spec:
  selector:
    app: driver-service
  ports:
    - name: http
      protocol: TCP
      port: 8004
      targetPort: 8004
    - name: grpc
      protocol: TCP
      port: 50054
      targetPort: 50054
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
  namespace: lastmile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
      - name: driver-service
        image: backend-driver_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8004
          name: http
        - containerPort: 50054
          name: grpc
        env:
        - name: DB_HOST
          value: "postgres-driver"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "driver_db"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: RABBITMQ_URL
          value: "amqp://admin:admin@rabbitmq:5672/"
        - name: LOCATION_SERVICE_HOST
          value: "location-service"
        - name: LOCATION_SERVICE_PORT
          value: "50056"
        - name: STATION_SERVICE_HOST
          value: "station-service"
        - name: STATION_SERVICE_PORT
          value: "50052"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-simulator
  namespace: lastmile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-simulator
  template:
    metadata:
      labels:
        app: driver-simulator
    spec:
      containers:
      - name: driver-simulator
        image: backend-driver_service:latest
        imagePullPolicy: Never
        command: ["python", "simulator_worker.py"]
        env:
        - name: DB_HOST
          value: "postgres-driver"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "driver_db"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: RABBITMQ_URL
          value: "amqp://admin:admin@rabbitmq:5672/"
        - name: LOCATION_SERVICE_HOST
          value: "location-service"
        - name: LOCATION_SERVICE_PORT
          value: "50056"
        - name: STATION_SERVICE_HOST
          value: "station-service"
        - name: STATION_SERVICE_PORT
          value: "50052"

